### ISSUE TITLE
Publish to open vsx

### ISSUE THREAD

**Issue by BLACK4585** [arrrrny/zed-one-theme-vs#1]
Hey, 
is it possible to publish your theme to https://open-vsx.org?

**Comment by arrrrny** [comment]
I just did https://open-vsx.org/extension/ARRRRNY/zed-one-theme

**Comment by BLACK4585** [comment]
Thabk you!

**Comment by arrrrny** [comment]
> Thabk you!

you can thank me by giving 5 stars in there
